### ISSUE TITLE
Plow Stuck

### ISSUE THREAD

**Issue by therealbill** [MennoMax/astikoor-horse-carts#17]
Unsure if this also applies to carts, but I've got my plow down a hill and it disconnects from the horse when trying to go back up. There appears to be no way to pick the cart back into inventory once play in the world. Adding a way to pick the cart back to inventory, or allow the horse to drag it back up the hill would be great thanks.

**Comment by therealbill** [comment]
Ah thanks, will try that.

**Comment by MennoMax** [comment]
Please tell me if it worked, so I can close this issue ^^

**Comment by therealbill** [comment]
It worked, thanks.
