### ISSUE TITLE
Crash when pressing hotkey on the ground

### ISSUE THREAD

**Issue by Snownee** [MennoMax/astikoor-horse-carts#18]
https://paste.dimdev.org/tetoqedawa.mccrash

**Comment by MennoMax** [comment]
Oh sorry, I forgot to push the latest version, this issue is only present in this repository, not in the alpha release ^^

**Comment by MennoMax** [comment]
https://github.com/MennoMax/astikoor-horse-carts/commit/b4c5b9e668b9a8d0b25cccfcc5223463a3f58d6c

Closed.
