### ISSUE TITLE
Plow overhaul

### ISSUE THREAD

**Issue by MennoMax** [MennoMax/astikoor-horse-carts#3]
Currently, it is too hard to properly plow grass. Following additions are necessary:

- plow inventory with a hoe slot, loses durability while plowing
- plowing width increased to 3 blocks
- grass and similar blocks should be destroyed when plowing
- farmland should stay tilled longer

**Comment by therealbill** [comment]
Hmm, perhaps a middle ground on plow width. Let the default be one wide, in the middle. Then use two inventory slots to hold additional plows to increase the width, up to three.

**Comment by MennoMax** [comment]
That might be even better, just a single inventory slot for the plow would look weird.  Also adding a visual representation of these additional plows to the model would be great.

**Comment by therealbill** [comment]
I was also thinking this morning that if you could put shovels in those slots they could make a path instead of tilling the ground. ;)

And yeah a visual representation would look sweet!
